name: tdd
description: Apprentissage a une architecture plus propre.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.19.6 <3.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  equatable: ^2.0.5
  dartz: ^0.10.1
  flutter_bloc: ^8.1.3
  http: ^0.13.6
  bloc: ^8.1.2
  get_it: ^7.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  mocktail: ^1.0.0
  bloc_test: ^9.1.4
flutter:
  uses-material-design: true
